name: Update Gradle repos with latest library version.
on:
  workflow_call:
    inputs:
      lib_name:
        type: string
        required: true
        description: |
          Name of the library repository.

          For example, "platform-common".
      lib_var:
        type: string
        required: true
        description: |
          Name of the variable in settings.gradle.kts for library version.

          For example, if the settings.gradle.kts file has this line,

            val socotraCommon = "0.8.2"

          then the value for lib_var should be "socotraCommon".
      lib_version:
        type: string
        required: true
        description: |
          New version of the library.

          For example, this might be "0.8.3" or "0.9.0".
      repos:
          type: string
          required: true
          description:
            JSON list of the repositories to check for dependency updates.
      is_hotfix:
          type: boolean
          required: false
          default: false
          description: |
            For rare event of hotfix to production, make hotfix branches instead of feature branches.

            Be sure to use lib_version with point value e.g. "1.6.114.1" to distinguish it from release.
      hotfix_target:
          type: string
          required: false
          default: "master"
          description: |
            The Base Branch for the hotfix PR. "master" if release is out or "release/{number}" if it went to staging.
    secrets:
      our_github_token:
        description: "Github API token, for checking out private repos."
jobs:
  main:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        repo: ${{ fromJSON(inputs.repos) }}
    steps:
    - name: Checkout service repo
      uses: actions/checkout@v3
      with:
        repository: socotra/${{ matrix.repo }}
        token: ${{ secrets.our_github_token }}
        path: /home/runner/work/${{ inputs.lib_name }}/${{ inputs.lib_name }}/repos/${{ matrix.repo }}
        ref: develop
        fetch-depth: 0
    - name: Update library version in settings.gradle.kts
      working-directory: /home/runner/work/${{ inputs.lib_name }}/${{ inputs.lib_name }}/repos/${{ matrix.repo }}
      run: |
        set -ex
        sed -E -i \
          's/(^\s*val ${{ inputs.lib_var }}\s*=\s*)\".*\"/\1\"${{ inputs.lib_version }}\"/' \
          settings.gradle.kts
    - name: Stage updates
      id: stage
      continue-on-error: true
      working-directory: /home/runner/work/${{ inputs.lib_name }}/${{ inputs.lib_name }}/repos/${{ matrix.repo }}
      run: |
        git add .
        # if nothing changed, then skip next step
        if [[ ! -n $(git status --porcelain --untracked-files=no) ]]; then
          exit 1
        fi
    - name: Create Feature Pull Requests
      if: ${{ (steps.stage.conclusion == 'success') && (inputs.is_hotfix == false) }}
      id: cfpr
      uses: peter-evans/create-pull-request@v4
      with:
        path: /home/runner/work/${{ inputs.lib_name }}/${{ inputs.lib_name }}/repos/${{ matrix.repo }}
        token: ${{ secrets.our_github_token }}
        branch: feature/update-${{ inputs.lib_name }}-${{ inputs.lib_version }}
        delete-branch: true
        base: develop
        reviewers: ${{ github.actor }}
        title: "Update dependency ${{ inputs.lib_name}} to version ${{ inputs.lib_version}}"
        commit-message: |
          Update dependency ${{ inputs.lib_name}} to version ${{ inputs.lib_version}}
        author: "Socotra DevOps <devops@socotra.com>"
    #- name: Enable auto-merge for feature branch
    #  if: ${{ (steps.stage.conclusion == 'success') && (inputs.is_hotfix == false) }}
    #  working-directory: /home/runner/work/${{ inputs.lib_name }}/${{ inputs.lib_name }}/repos/${{ matrix.repo }}
    #  run: |
    #    if [[ -z "${{ steps.cfpr.outputs.pull-request-number }}" ]]; then
    #      exit 0
    #    fi
    #    gh pr merge \
    #      "feature/update-${{ inputs.lib_name }}-${{ inputs.lib_version }}" \
    #      -R "socotra/${{ matrix.repo }}" \
    #      -b "Merge: Update dependency ${{ inputs.lib_name}} to version ${{ inputs.lib_version}}" \
    #      -A "Socotra DevOps <devops@socotra.com>" \
    #      --merge --auto --admin
    #  env:
    #    GITHUB_TOKEN: "${{ secrets.our_github_token }}"
    #  #uses: peter-evans/enable-pull-request-automerge@v3
    #  #with:
    #  #  token: ${{ secrets.our_github_token }}
    #  #  repository: socotra/${{ matrix.repo }}
    #  #  pull-request-number: ${{ steps.cfpr.outputs.pull-request-number }}
    - name: Create Hotfix Pull Request
      if: ${{ (steps.stage.conclusion == 'success') && (inputs.is_hotfix == true) }}
      uses: peter-evans/create-pull-request@v7.0.8
      with:
        path: /home/runner/work/${{ inputs.lib_name }}/${{ inputs.lib_name }}/repos/${{ matrix.repo }}
        token: ${{ secrets.our_github_token }}
        branch: hotfix/update-${{ inputs.lib_name }}-${{ inputs.lib_version }}
        delete-branch: true
        base: master
        reviewers: ${{ github.actor }}
        title: "Hotfix dependency ${{ inputs.lib_name}} to version ${{ inputs.lib_version}}"
        commit-message: |
          Hotfix dependency ${{ inputs.lib_name}} to version ${{ inputs.lib_version}}
        author: "Socotra DevOps <devops@socotra.com>"
